server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    types {
        application/javascript js mjs;
    }

    location / {
        try_files $uri /index.html;
    }
}
